# Contents
The purpose of this notebook is to investigate the implementation of symmetry operations to determine a solution for reconstructing a general crystal structure

In [33]:
from hexomap.RotRep import GetSymRotMat
from hexomap.orientation import Quaternion
from hexomap.sim_utilities import getLatticeVectors

import numpy as np

### Cubic Symmetry Test

In [20]:
sqrt2 = np.sqrt(2)
quats_432 = [Quaternion(*me) for me in [
        [ 1.0,        0.0,        0.0,        0.0       ], # Identity
        [ 0.0,        1.0,        0.0,        0.0       ], # 180/[100]
        [ 0.0,        0.0,        1.0,        0.0       ], # 180/[010]
        [ 0.0,        0.0,        0.0,        1.0       ], # 180/[001]
        [ 0.0,        0.0,        0.5*sqrt2,  0.5*sqrt2 ], # 180/[011]
        [ 0.0,        0.0,        0.5*sqrt2, -0.5*sqrt2 ], # 180/[01-1]
        [ 0.0,        0.5*sqrt2,  0.0,        0.5*sqrt2 ], # 180/[101]
        [ 0.0,        0.5*sqrt2,  0.0,       -0.5*sqrt2 ], # 180/[10-1]
        [ 0.0,        0.5*sqrt2, -0.5*sqrt2,  0.0       ], # 180/[1-10]
        [ 0.0,       -0.5*sqrt2, -0.5*sqrt2,  0.0       ], # 180/[-1-10]
        [ 0.5,        0.5,        0.5,        0.5       ], # 120/[111]
        [-0.5,        0.5,        0.5,        0.5       ], # -120/[111]
        [-0.5,        0.5,        0.5,       -0.5       ], # -120/[11-1]
        [-0.5,        0.5,       -0.5,        0.5       ], # -120/[1-11]
        [-0.5,       -0.5,        0.5,        0.5       ], # -120/[-111]
        [-0.5,       -0.5,        0.5,       -0.5       ], # -120/[-11-1]
        [-0.5,       -0.5,       -0.5,        0.5       ], # -120/[-1-11]
        [-0.5,        0.5,       -0.5,       -0.5       ], # -120/[1-1-1]
        [-0.5*sqrt2,  0.0,        0.0,        0.5*sqrt2 ], # -90/[001]
        [ 0.5*sqrt2,  0.0,        0.0,        0.5*sqrt2 ], # 90/[001]
        [-0.5*sqrt2,  0.0,        0.5*sqrt2,  0.0       ], # -90/[010]
        [-0.5*sqrt2,  0.0,       -0.5*sqrt2,  0.0       ], # -90/[0-10]
        [-0.5*sqrt2,  0.5*sqrt2,  0.0,        0.0       ], # -90/[100]
        [-0.5*sqrt2, -0.5*sqrt2,  0.0,        0.0       ], # -90/[-100]
    ]
]

In [44]:
with np.printoptions(precision=5, suppress=True):
    print(np.array([q.as_matrix for q in quats_432], dtype=np.int64))

[[[ 1  0  0]
  [ 0  1  0]
  [ 0  0  1]]

 [[ 1  0  0]
  [ 0 -1  0]
  [ 0  0 -1]]

 [[-1  0  0]
  [ 0  1  0]
  [ 0  0 -1]]

 [[-1  0  0]
  [ 0 -1  0]
  [ 0  0  1]]

 [[-1  0  0]
  [ 0  0  1]
  [ 0  1  0]]

 [[-1  0  0]
  [ 0  0 -1]
  [ 0 -1  0]]

 [[ 0  0  1]
  [ 0 -1  0]
  [ 1  0  0]]

 [[ 0  0 -1]
  [ 0 -1  0]
  [-1  0  0]]

 [[ 0 -1  0]
  [-1  0  0]
  [ 0  0 -1]]

 [[ 0  1  0]
  [ 1  0  0]
  [ 0  0 -1]]

 [[ 0  0  1]
  [ 1  0  0]
  [ 0  1  0]]

 [[ 0  1  0]
  [ 0  0  1]
  [ 1  0  0]]

 [[ 0  0 -1]
  [ 1  0  0]
  [ 0 -1  0]]

 [[ 0  0  1]
  [-1  0  0]
  [ 0 -1  0]]

 [[ 0  0 -1]
  [-1  0  0]
  [ 0  1  0]]

 [[ 0 -1  0]
  [ 0  0 -1]
  [ 1  0  0]]

 [[ 0  1  0]
  [ 0  0 -1]
  [-1  0  0]]

 [[ 0 -1  0]
  [ 0  0  1]
  [-1  0  0]]

 [[ 0  1  0]
  [-1  0  0]
  [ 0  0  1]]

 [[ 0 -1  0]
  [ 1  0  0]
  [ 0  0  1]]

 [[ 0  0 -1]
  [ 0  1  0]
  [ 1  0  0]]

 [[ 0  0  1]
  [ 0  1  0]
  [-1  0  0]]

 [[ 1  0  0]
  [ 0  0  1]
  [ 0 -1  0]]

 [[ 1  0  0]
  [ 0  0 -1]
  [ 0  1  0]]]


In [45]:
mat_432 = GetSymRotMat(symtype='Cubic')
with np.printoptions(precision=5, suppress=True):
    print(mat_432.astype(np.int64))

[[[ 0  1  0]
  [-1  0  0]
  [ 0  0  1]]

 [[-1  0  0]
  [ 0 -1  0]
  [ 0  0  1]]

 [[ 0 -1  0]
  [ 1  0  0]
  [ 0  0  1]]

 [[ 0  0 -1]
  [ 0  1  0]
  [ 1  0  0]]

 [[-1  0  0]
  [ 0  1  0]
  [ 0  0 -1]]

 [[ 0  0  1]
  [ 0  1  0]
  [-1  0  0]]

 [[ 1  0  0]
  [ 0  0  1]
  [ 0 -1  0]]

 [[ 1  0  0]
  [ 0 -1  0]
  [ 0  0 -1]]

 [[ 1  0  0]
  [ 0  0 -1]
  [ 0  1  0]]

 [[ 0  1  0]
  [ 0  0  1]
  [ 1  0  0]]

 [[ 0  0  1]
  [ 1  0  0]
  [ 0  1  0]]

 [[ 0  0 -1]
  [ 1  0  0]
  [ 0 -1  0]]

 [[ 0  1  0]
  [ 0  0 -1]
  [-1  0  0]]

 [[ 0  0  1]
  [-1  0  0]
  [ 0 -1  0]]

 [[ 0 -1  0]
  [ 0  0 -1]
  [ 1  0  0]]

 [[ 0  0 -1]
  [-1  0  0]
  [ 0  1  0]]

 [[ 0 -1  0]
  [ 0  0  1]
  [-1  0  0]]

 [[-1  0  0]
  [ 0  0  1]
  [ 0  1  0]]

 [[ 0  0  1]
  [ 0 -1  0]
  [ 1  0  0]]

 [[ 0  1  0]
  [ 1  0  0]
  [ 0  0 -1]]

 [[-1  0  0]
  [ 0  0 -1]
  [ 0 -1  0]]

 [[ 0  0 -1]
  [ 0 -1  0]
  [-1  0  0]]

 [[ 0 -1  0]
  [-1  0  0]
  [ 0  0 -1]]

 [[ 1  0  0]
  [ 0  1  0]
  [ 0  0  1]]]


By hand, I've confirmed these are the same lists and contain all the required operators\
It was not enjoyable

Now to write a function that generates and applies the transform to move the quaternions into Cartesian\
For the cubic case, it should generate the identity

In [46]:
from hexomap.sim_utilities import getLatticeVectors

In [56]:
a, b, c = getLatticeVectors(3.54,3.54,3.54,90,90,90)
print(a,b,c)
P = np.column_stack([a,b,c])
P_inv = np.linalg.inv(P)
print(P)
print(P_inv)
quat_asMat_c = np.array([q.as_matrix for q in quats_432], dtype=np.int64)
quat_asMat_s = np.array([P_inv@quat_asMat_c[m]@P for m in range(quat_asMat_c.shape[0])])
with np.printoptions(precision=5, suppress=True):
    print(quat_asMat_s)

[3.54 0.   0.  ] [2.16762483e-16 3.54000000e+00 0.00000000e+00] [2.16762483e-16 2.16762483e-16 3.54000000e+00]
[[3.54000000e+00 2.16762483e-16 2.16762483e-16]
 [0.00000000e+00 3.54000000e+00 2.16762483e-16]
 [0.00000000e+00 0.00000000e+00 3.54000000e+00]]
[[ 2.82485876e-01 -1.72972712e-17 -1.72972712e-17]
 [ 0.00000000e+00  2.82485876e-01 -1.72972712e-17]
 [ 0.00000000e+00  0.00000000e+00  2.82485876e-01]]
[[[ 1. -0. -0.]
  [ 0.  1. -0.]
  [ 0.  0.  1.]]

 [[ 1.  0.  0.]
  [ 0. -1.  0.]
  [ 0.  0. -1.]]

 [[-1. -0.  0.]
  [ 0.  1.  0.]
  [ 0.  0. -1.]]

 [[-1.  0. -0.]
  [ 0. -1. -0.]
  [ 0.  0.  1.]]

 [[-1. -0. -0.]
  [ 0. -0.  1.]
  [ 0.  1.  0.]]

 [[-1.  0.  0.]
  [ 0.  0. -1.]
  [ 0. -1. -0.]]

 [[-0.  0.  1.]
  [-0. -1. -0.]
  [ 1.  0.  0.]]

 [[ 0.  0. -1.]
  [ 0. -1. -0.]
  [-1. -0. -0.]]

 [[ 0. -1.  0.]
  [-1. -0.  0.]
  [ 0.  0. -1.]]

 [[-0.  1.  0.]
  [ 1.  0.  0.]
  [ 0.  0. -1.]]

 [[-0. -0.  1.]
  [ 1. -0.  0.]
  [ 0.  1.  0.]]

 [[-0.  1. -0.]
  [-0. -0.  1.]
  [ 1.  

So unsurprisingly that doesn't really do anything because the cubic frame is already aligned with the Cartesian frame

### Hexagonal Symmetry Test

In [59]:
sqrt3 = np.sqrt(3)
quats_622 = [Quaternion(*me) for me in [
        [ 1.0,        0.0,        0.0,        0.0       ],
        [-0.5*sqrt3,  0.0,        0.0,       -0.5       ],
        [ 0.5,        0.0,        0.0,        0.5*sqrt3 ],
        [ 0.0,        0.0,        0.0,        1.0       ],
        [-0.5,        0.0,        0.0,        0.5*sqrt3 ],
        [-0.5*sqrt3,  0.0,        0.0,        0.5       ],
        [ 0.0,        1.0,        0.0,        0.0       ],
        [ 0.0,       -0.5*sqrt3,  0.5,        0.0       ],
        [ 0.0,        0.5,       -0.5*sqrt3,  0.0       ],
        [ 0.0,        0.0,        1.0,        0.0       ],
        [ 0.0,       -0.5,       -0.5*sqrt3,  0.0       ],
        [ 0.0,        0.5*sqrt3,  0.5,        0.0       ],
    ]
]
with np.printoptions(precision=5, suppress=True):
    print(np.array([q.as_matrix for q in quats_622]))

[[[ 1.      -0.       0.     ]
  [ 0.       1.      -0.     ]
  [ 0.       0.       1.     ]]

 [[ 0.5     -0.86603 -0.     ]
  [ 0.86603  0.5      0.     ]
  [-0.      -0.       1.     ]]

 [[-0.5     -0.86603  0.     ]
  [ 0.86603 -0.5     -0.     ]
  [ 0.       0.       1.     ]]

 [[-1.      -0.       0.     ]
  [ 0.      -1.      -0.     ]
  [ 0.       0.       1.     ]]

 [[-0.5      0.86603  0.     ]
  [-0.86603 -0.5      0.     ]
  [ 0.      -0.       1.     ]]

 [[ 0.5      0.86603  0.     ]
  [-0.86603  0.5      0.     ]
  [ 0.      -0.       1.     ]]

 [[ 1.       0.       0.     ]
  [ 0.      -1.      -0.     ]
  [ 0.       0.      -1.     ]]

 [[ 0.5     -0.86603  0.     ]
  [-0.86603 -0.5      0.     ]
  [-0.      -0.      -1.     ]]

 [[-0.5     -0.86603 -0.     ]
  [-0.86603  0.5     -0.     ]
  [ 0.       0.      -1.     ]]

 [[-1.      -0.       0.     ]
  [-0.       1.      -0.     ]
  [-0.      -0.      -1.     ]]

 [[-0.5      0.86603 -0.     ]
  [ 0.86603  0.5   

In [32]:
mat_622 = GetSymRotMat(symtype='Hexagonal')
with np.printoptions(precision=5, suppress=True):
    print(mat_622)

[[[ 0.5     -0.86603  0.     ]
  [ 0.86603  0.5      0.     ]
  [ 0.       0.       1.     ]]

 [[-0.5     -0.86603  0.     ]
  [ 0.86603 -0.5      0.     ]
  [ 0.       0.       1.     ]]

 [[-1.      -0.       0.     ]
  [ 0.      -1.       0.     ]
  [ 0.       0.       1.     ]]

 [[-0.5      0.86603  0.     ]
  [-0.86603 -0.5      0.     ]
  [ 0.       0.       1.     ]]

 [[ 0.5      0.86603  0.     ]
  [-0.86603  0.5      0.     ]
  [ 0.       0.       1.     ]]

 [[ 1.       0.       0.     ]
  [ 0.       1.       0.     ]
  [ 0.       0.       1.     ]]

 [[ 1.       0.       0.     ]
  [ 0.      -1.       0.     ]
  [ 0.       0.      -1.     ]]

 [[ 0.5      0.86603  0.     ]
  [ 0.86603 -0.5      0.     ]
  [ 0.       0.      -1.     ]]

 [[-0.5      0.86603  0.     ]
  [ 0.86603  0.5      0.     ]
  [ 0.       0.      -1.     ]]

 [[-1.       0.       0.     ]
  [ 0.       1.       0.     ]
  [ 0.       0.      -1.     ]]

 [[-0.5     -0.86603  0.     ]
  [-0.86603  0.5   

First, the operations in RotRep and orientation are the exact same lists\
So the Hexagonal operators are both using an orthonormal frame rather than the hexagonal one\
This proabably means the other structures with non-orthonormal frames will be a bit tricky

## Plan

Write down all symmetry operations as matrices acting on crystal frames in reference frame of crystal\
This means hexagonal, trigonal, etc are using their inherent coordinate systems rather than orthonormal ones\
Generate direct structure matrix from crystal structure\
Use a*m\*a^-1 to convert to Cartesian frame\
Verify this produces the correct matrices for already implemented cubic and hexagonal\
Change CrystalStr class definition to generate and store these operators on initialization

### Defining Operators

In [49]:
# These are the Crystal Frame operators as matrices
def GetSymRotMat_new(symtype='Cubic'):
    if symtype in [str(spg) for spg in range(1,2+1)]:
        # Triclinic
        m = np.zeros((1,3,3))
        # Identity
        m[0] = [[1,0,0],
                [0,1,0],
                [0,0,1]]
        return m
    
    elif symtype in [str(spg) for spg in range(3,15+1)]:
        # Monoclinic
        m = np.zeros((2,3,3))
        # Identity
        m[0] = [[1,0,0],
                [0,1,0],
                [0,0,1]]
        # 2-fold || b
        m[1] = [[-1,0,0],
                [0,1,0],
                [0,0,-1]]
        return m
    
    elif symtype in [str(spg) for spg in range(16,74+1)]:
        # Orthorhombic
        m = np.zeros((4,3,3))
        # Identity
        m[0] = [[1,0,0],
                [0,1,0],
                [0,0,1]]
        # 2-fold || a
        m[1] = [[1,0,0],
                [0,-1,0],
                [0,0,-1]]    
        # 2-fold || b
        m[2] = [[-1,0,0],
                [0,1,0],
                [0,0,-1]]
        # 2-fold || c
        m[3] = [[-1,0,0],
                [0,-1,0],
                [0,0,1]]
        return m
        
    elif symtype in [str(spg) for spg in range(75,88+1)]:
        m = np.zeros((4,3,3))
        # Tetragonal_lower
        # Identity
        m[0] = [[1,0,0],
                [0,1,0],
                [0,0,1]]
        # 2-fold || c
        m[1] = [[-1,0,0],
                [0,-1,0],
                [0,0,1]]    
        # 4-fold || c
        m[2] = [[0,-1,0],
                [1,0,0],
                [0,0,1]]
        # 4-fold || c
        m[3] = m[2].T
        return m
        
    elif symtype == 'Tetragonal' or symtype in [str(spg) for spg in range(89,142+1)]:
        m = np.zeros((8, 3, 3))
        # Tetragonal
        # Identity
        m[0] = [[1,0,0],
                [0,1,0],
                [0,0,1]]
        # 2-fold || c
        m[1] = [[-1,0,0],
                [0,-1,0],
                [0,0,1]]    
        # 4-fold || c
        m[2] = [[0,-1,0],
                [1,0,0],
                [0,0,1]]
        # 4-fold || c
        m[3] = m[2].T
        # 2-fold || a
        m[4] = [[1,0,0],
                [0,-1,0],
                [0,0,-1]]    
        # 2-fold || b
        m[5] = [[-1,0,0],
                [0,1,0],
                [0,0,-1]]
        # 2-fold || [110]
        m[6] = [[0,1,0],
                [1,0,0],
                [0,0,-1]]
        # 2-fold || [1-10]
        m[7] = [[0,-1,0],
                [-1,0,0],
                [0,0,-1]]
        return m

    elif symtype in [str(spg) for spg in range(143,148+1)]:
        m = np.zeros((3,3,3))
        # Trigonal_lower
        # Identity
        m[0] = [[1,0,0],
                [0,1,0],
                [0,0,1]]
        # 3-fold || [111]
        m[1] = [[0,0,1],
                [1,0,0],
                [0,1,0]]
        # 3-fold || [111]
        m[2] = m[1].T
        return m

    elif symtype in [str(spg) for spg in range(149,167+1)]:
        m = np.zeros((6,3,3))
        # Trigonal
        # Identity
        m[0] = [[1,0,0],
                [0,1,0],
                [0,0,1]]
        # 3-fold || [111]
        m[1] = [[0,0,1],
                [1,0,0],
                [0,1,0]]
        # 3-fold || [111]
        m[2] = m[1].T
        # 2-fold || a
        m[3] = [[1,0,0],
                [0,-1,0],
                [0,0,-1]]    
        # 2-fold || b
        m[4] = [[-1,0,0],
                [0,1,0],
                [0,0,-1]]
        # 2-fold || c
        m[5] = [[-1,0,0],
                [0,-1,0],
                [0,0,1]]
        return m

    elif symtype in [str(spg) for spg in range(168,176+1)]:
        m = np.zeros((6,3,3))
        # Hexagonal_lower
        # Identity
        m[0] = [[1,0,0],
                [0,1,0],
                [0,0,1]]
        # 2-fold || c
        m[1] = [[-1,0,0],
                [0,-1,0],
                [0,0,1]]
        # 3-fold || c
        m[2] = [[0,-1,0],
                [1,-1,0],
                [0,0,1]]
        # 3-fold || c
        m[3] = [[-1,1,0],
                [-1,0,0],
                [0,0,1]]
        # 6-fold || c
        m[4] = [[1,-1,0],
                [1,0,0],
                [0,0,1]]
        # 6-fold || c
        m[5] = [[0,1,0],
                [-1,1,0],
                [0,0,1]]
        return m

    elif symtype == 'Hexagonal' or symtype in [str(spg) for spg in range(177,194+1)]:
        m = np.zeros((12, 3, 3))
        # Hexagonal
        # Identity
        m[0] = [[1,0,0],
                [0,1,0],
                [0,0,1]]
        # 2-fold || c
        m[1] = [[-1,0,0],
                [0,-1,0],
                [0,0,1]]
        # 3-fold || c
        m[2] = [[0,-1,0],
                [1,-1,0],
                [0,0,1]]
        # 3-fold || c
        m[3] = [[-1,1,0],
                [-1,0,0],
                [0,0,1]]
        # 6-fold || c
        m[4] = [[1,-1,0],
                [1,0,0],
                [0,0,1]]
        # 6-fold || c
        m[5] = [[0,1,0],
                [-1,1,0],
                [0,0,1]]
        # 2-fold || a
        m[6] = [[1,-1,0],
                [0,-1,0],
                [0,0,-1]]
        # 2-fold || b
        m[7] = [[-1,0,0],
                [-1,1,0],
                [0,0,-1]]
        # 2-fold || [110]
        m[8] = [[0,1,0],
                [1,0,0],
                [0,0,-1]]
        # 2-fold || [1-10]
        m[9] = [[0,-1,0],
                [-1,0,0],
                [0,0,-1]]
        # 2-fold || [210]
        m[10] = [[1,0,0],
                [1,-1,0],
                [0,0,-1]]
        # 2-fold || [120]
        m[11] = [[-1,1,0],
                [0,1,0],
                [0,0,-1]]
        return m
        
    elif symtype in [str(spg) for spg in range(195,206+1)]:
        m = np.zeros((12,3,3))
        # Cubic_lower
        # Identity
        m[0] = [[1,0,0],
               [0,1,0],
               [0,0,1]]
        # 2-fold || a
        m[1] = [[1,0,0],
               [0,-1,0],
               [0,0,-1]]
        # 2-fold || b
        m[2] = [[-1,0,0],
               [0,1,0],
               [0,0,-1]]
        # 2-fold || c
        m[3] = [[-1,0,0],
               [0,-1,0],
               [0,0,1]]
        # 3-fold || [111]
        m[4] = [[0,0,1],
               [1,0,0],
               [0,1,0]]
        # 3-fold || [111]
        m[5] = m[4].T
        # 3-fold || [1-1-1]
        m[6] = [[0,0,-1],
               [-1,0,0],
               [0,1,0]]
        # 3-fold || [1-1-1]
        m[7] = m[6].T
        # 3-fold || [-11-1]
        m[8] = [[0,0,1],
               [-1,0,0],
               [0,-1,0]]
        # 3-fold || [-11-1]
        m[9] = m[8].T
        # 3-fold || [-1-11]
        m[10] = [[0,0,-1],
               [1,0,0],
               [0,-1,0]]
        # 3-fold || [-1-11]
        m[11] = m[10].T
        return m

    elif symtype == 'Cubic' or symtype in [str(spg) for spg in range(207,230+1)]:
        m = np.zeros((24, 3, 3))
        # Cubic
        # Identity
        m[0] = [[1,0,0],
               [0,1,0],
               [0,0,1]]
        # 2-fold || a
        m[1] = [[1,0,0],
               [0,-1,0],
               [0,0,-1]]
        # 2-fold || b
        m[2] = [[-1,0,0],
               [0,1,0],
               [0,0,-1]]
        # 2-fold || c
        m[3] = [[-1,0,0],
               [0,-1,0],
               [0,0,1]]
        # 3-fold || [111]
        m[4] = [[0,0,1],
               [1,0,0],
               [0,1,0]]
        # 3-fold || [111]
        m[5] = m[4].T
        # 3-fold || [1-1-1]
        m[6] = [[0,0,-1],
               [-1,0,0],
               [0,1,0]]
        # 3-fold || [1-1-1]
        m[7] = m[6].T
        # 3-fold || [-11-1]
        m[8] = [[0,0,1],
               [-1,0,0],
               [0,-1,0]]
        # 3-fold || [-11-1]
        m[9] = m[8].T
        # 3-fold || [-1-11]
        m[10] = [[0,0,-1],
               [1,0,0],
               [0,-1,0]]
        # 3-fold || [-1-11]
        m[11] = m[10].T
        # 2-fold || [110]
        m[12] = [[0,1,0],
                 [1,0,0],
                 [0,0,-1]]
        # 2-fold || [1-10]
        m[13] = [[0,-1,0],
                 [-1,0,0],
                 [0,0,-1]]
        # 2-fold || [101]
        m[14] = [[0,0,1],
                 [0,-1,0],
                 [1,0,0]]
        # 2-fold || [-101]
        m[15] = [[0,0,-1],
                 [0,-1,0],
                 [-1,0,0]]
        # 2-fold || [011]
        m[16] = [[-1,0,0],
                 [0,0,1],
                 [0,1,0]]
        # 2-fold || [01-1]
        m[17] = [[-1,0,0],
                 [0,0,-1],
                 [0,-1,0]]
        # 4-fold || a
        m[18] = [[1,0,0],
                 [0,0,-1],
                 [0,1,0]]
        # 4-fold || a
        m[19] = m[18].T
        # 4-fold || b
        m[20] = [[0,0,1],
                 [0,1,0],
                 [-1,0,0]]
        # 4-fold || b
        m[21] = m[20].T
        # 4-fold || c
        m[22] = [[0,-1,0],
                 [1,0,0],
                 [0,0,1]]
        # 4-fold || c
        m[23] = m[22].T
        return m

In [57]:
test = GetSymRotMat_new('194')
print(test)

[[[ 1.  0.  0.]
  [ 0.  1.  0.]
  [ 0.  0.  1.]]

 [[-1.  0.  0.]
  [ 0. -1.  0.]
  [ 0.  0.  1.]]

 [[ 0. -1.  0.]
  [ 1. -1.  0.]
  [ 0.  0.  1.]]

 [[-1.  1.  0.]
  [-1.  0.  0.]
  [ 0.  0.  1.]]

 [[ 1. -1.  0.]
  [ 1.  0.  0.]
  [ 0.  0.  1.]]

 [[ 0.  1.  0.]
  [-1.  1.  0.]
  [ 0.  0.  1.]]

 [[ 1. -1.  0.]
  [ 0. -1.  0.]
  [ 0.  0. -1.]]

 [[-1.  0.  0.]
  [-1.  1.  0.]
  [ 0.  0. -1.]]

 [[ 0.  1.  0.]
  [ 1.  0.  0.]
  [ 0.  0. -1.]]

 [[ 0. -1.  0.]
  [-1.  0.  0.]
  [ 0.  0. -1.]]

 [[ 1.  0.  0.]
  [ 1. -1.  0.]
  [ 0.  0. -1.]]

 [[-1.  1.  0.]
  [ 0.  1.  0.]
  [ 0.  0. -1.]]]


In [52]:
def directStructureMatrix(a_vec, b_vec, c_vec):
    dsm = np.column_stack([a_vec, b_vec, c_vec])
    return dsm
def op2Cart(op, dsm):
    op_cart = np.dot(dsm, np.dot(op, np.linalg.inv(dsm)))
    return op_cart

In [59]:
a_vec, b_vec, c_vec = getLatticeVectors(2.95,2.95,4.68,90,90,120)
dsm = directStructureMatrix(a_vec, b_vec, c_vec)
op_crys = GetSymRotMat_new('194')
num = op_crys.shape[0]
op_cart = np.zeros((num,3,3))
for op in range(num):
    op_cart[op] = op2Cart(op_crys[op], dsm)
print(np.round(op_cart,5))

[[[ 1.       0.       0.     ]
  [ 0.       1.       0.     ]
  [ 0.       0.       1.     ]]

 [[-1.      -0.       0.     ]
  [ 0.      -1.       0.     ]
  [ 0.       0.       1.     ]]

 [[-0.5     -0.86603  0.     ]
  [ 0.86603 -0.5      0.     ]
  [ 0.       0.       1.     ]]

 [[-0.5      0.86603  0.     ]
  [-0.86603 -0.5      0.     ]
  [ 0.       0.       1.     ]]

 [[ 0.5     -0.86603  0.     ]
  [ 0.86603  0.5      0.     ]
  [ 0.       0.       1.     ]]

 [[ 0.5      0.86603 -0.     ]
  [-0.86603  0.5      0.     ]
  [ 0.       0.       1.     ]]

 [[ 1.      -0.      -0.     ]
  [ 0.      -1.      -0.     ]
  [ 0.       0.      -1.     ]]

 [[-0.5     -0.86603  0.     ]
  [-0.86603  0.5     -0.     ]
  [ 0.       0.      -1.     ]]

 [[-0.5      0.86603 -0.     ]
  [ 0.86603  0.5     -0.     ]
  [ 0.       0.      -1.     ]]

 [[ 0.5     -0.86603  0.     ]
  [-0.86603 -0.5     -0.     ]
  [ 0.       0.      -1.     ]]

 [[ 0.5      0.86603 -0.     ]
  [ 0.86603 -0.5   

In [61]:
print(np.round(GetSymRotMat('194'),5))

[[[ 0.5     -0.86603  0.     ]
  [ 0.86603  0.5      0.     ]
  [ 0.       0.       1.     ]]

 [[-0.5     -0.86603  0.     ]
  [ 0.86603 -0.5      0.     ]
  [ 0.       0.       1.     ]]

 [[-1.      -0.       0.     ]
  [ 0.      -1.       0.     ]
  [ 0.       0.       1.     ]]

 [[-0.5      0.86603  0.     ]
  [-0.86603 -0.5      0.     ]
  [ 0.       0.       1.     ]]

 [[ 0.5      0.86603  0.     ]
  [-0.86603  0.5      0.     ]
  [ 0.       0.       1.     ]]

 [[ 1.       0.       0.     ]
  [ 0.       1.       0.     ]
  [ 0.       0.       1.     ]]

 [[ 1.       0.       0.     ]
  [ 0.      -1.       0.     ]
  [ 0.       0.      -1.     ]]

 [[ 0.5      0.86603  0.     ]
  [ 0.86603 -0.5      0.     ]
  [ 0.       0.      -1.     ]]

 [[-0.5      0.86603  0.     ]
  [ 0.86603  0.5      0.     ]
  [ 0.       0.      -1.     ]]

 [[-1.       0.       0.     ]
  [ 0.       1.       0.     ]
  [ 0.       0.      -1.     ]]

 [[-0.5     -0.86603  0.     ]
  [-0.86603  0.5   

Method generates the same symmetry operators as before for hexagonal

To do:\
Add symmetry operators to file\
Add generation of Cartesian operators\
Remove old references